apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs-{{ default "staging" .Release.Namespace }}-php
  namespace: {{ default "staging" .Release.Namespace }}
  labels:
    tier: backend
  annotations:
    "builddate": "20220812-01"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cs-{{ default "staging" .Release.Namespace }}-php
      tier: backend
  template:
    metadata:
      labels:
        app: cs-{{ default "staging" .Release.Namespace }}-php
        tier: backend
        {{ if ne .Release.Namespace "production" }}name: cs-{{ .Release.Namespace }}{{- else }}hostname: cs{{- end }}
    spec:
      containers:
      - name: cs-{{ default "staging" .Release.Namespace }}-php
        image: php:8-fpm
        volumeMounts:
        - mountPath: /var/www/html
          name: webroot
          readOnly: true
      volumes:
      - name: webroot
        nfs:
          path: /calvincsaks/csweb/html
          server: calvincsaks.file.core.windows.net
