apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs-{{ default "staging" .Release.Namespace }}-php
  namespace: {{ default "staging" .Release.Namespace }}
  labels:
    tier: backend
  annotations:
    "builddate": "20230215-01"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cs-{{ default "staging" .Release.Namespace }}-php
      tier: backend
  template:
    metadata:
      annotations:
        releaseTime: {{ dateInZone "2006-01-02 15:04:05Z" (now) "UTC"| quote }}
      labels:
        app: cs-{{ default "staging" .Release.Namespace }}-php
        tier: backend
        {{ if ne .Release.Namespace "production" }}name: cs-{{ .Release.Namespace }}{{- else }}hostname: cs{{- end }}
    spec:
      containers:
      - name: cs-{{ default "staging" .Release.Namespace }}-php
        image: php:8-fpm
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "/usr/local/bin/php-add-ldap.sh"]
        resources:
          requests:
            memory: "50Mi"
            cpu: "100m" # 0.1 CPU
          limits:
            memory: "100Mi"
            cpu: "200m" # 0.2 CPU
        volumeMounts:
        - mountPath: /var/www/html
          name: webroot
          readOnly: true
        - mountPath: /etc/ssl/certs/CalvinCollege-ad-CA.crt
          name: config
          subPath: CalvinCollege-ad-CA.crt
          readOnly: true
        - mountPath: /etc/ssl/certs/ddbc78f4.0
          name: config
          subPath: ddbc78f4.0
          readOnly: true
        - mountPath: /usr/local/bin/php-add-ldap.sh
          name: phpconfig
          subPath: php-add-ldap.sh
          readOnly: true
      volumes:
      - name: webroot
        nfs:
          path: /export/csweb/html
          server: cswebnfs-int.k8s.cs.calvin.edu
      - name: config
        configMap:
          name: cs-{{ default "staging" .Release.Namespace }}-nginx-config
          items:
          - key: calvinadcert
            path: CalvinCollege-ad-CA.crt
          - key: calvinadcert
            path: ddbc78f4.0
      - name: phpconfig
        configMap:
          name: cs-{{ default "staging" .Release.Namespace }}-nginx-config
          defaultMode: 0777
          items:
          - key: phpaddldap
            path: php-add-ldap.sh
---
{{ if eq .Release.Namespace "production" }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cs-php-{{ default "staging" .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cs-{{ default "staging" .Release.Namespace }}-php
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  #  metrics:
  #- type: Resource
  #  resource:
  #    name: cpu
  #    target:
  #      type: Utilization
  #      averageUtilization: 80
  #- type: Resource
  #  resource:
  #    name: memory
  #    target:
  #      type: Utilization
  #      averageUtilization: 80
{{- end }}

