apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs-{{ default "staging" .Release.Namespace }}-php
  namespace: {{ default "staging" .Release.Namespace }}
  labels:
    tier: backend
  annotations:
    "builddate": "20230309-1"
spec:
  {{ if eq .Release.Namespace "production" }}replicas: 1{{- else }}replicas: 2{{- end }}
  selector:
    matchLabels:
      app: cs-{{ default "staging" .Release.Namespace }}-php
      tier: backend
  template:
    metadata:
      annotations:
        releaseTime: {{ dateInZone "2006-01-02 15:04:05Z" (now) "UTC"| quote }}
      labels:
        app: cs-{{ default "staging" .Release.Namespace }}-php
        tier: backend
        {{ if ne .Release.Namespace "production" }}name: cs-{{ .Release.Namespace }}{{- else }}hostname: cs{{- end }}
    spec:
      containers:
      - name: cs-{{ default "staging" .Release.Namespace }}-php
        image: php:8-fpm
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "/usr/local/bin/php-configure-podstart.sh"]
        livenessProbe:
          exec:
            command:
              - php-fpm-healthcheck
              - --listen-queue=15 # fails if there are more than 10 processes waiting in the fpm queue
              - --accepted-conn=5000 # fails after fpm has served more than 5k requests, this will force the pod to reset, use with caution
          initialDelaySeconds: 60
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
              - php-fpm-healthcheck # a simple ping since this means it's ready to handle traffic
          initialDelaySeconds: 30
          periodSeconds: 5
        resources:
          requests:
            memory: "100Mi"
            cpu: "200m" # 0.2 CPU
          limits:
            memory: "100Mi"
            cpu: "400m" # 0.4 CPU
        volumeMounts:
        - mountPath: /var/www/html
          name: webroot
          readOnly: true
        - mountPath: /etc/ssl/certs/CalvinCollege-ad-CA.crt
          name: config
          subPath: CalvinCollege-ad-CA.crt
          readOnly: true
        - mountPath: /etc/ssl/certs/ddbc78f4.0
          name: config
          subPath: ddbc78f4.0
          readOnly: true
        - mountPath: /usr/local/bin/php-configure-podstart.sh
          name: phpconfig
          subPath: php-configure-podstart.sh
          readOnly: true
      volumes:
      - name: webroot
        nfs:
          path: /export/csweb/html
          server: cswebnfs-int.k8s.cs.calvin.edu
      - name: config
        configMap:
          name: cs-{{ default "staging" .Release.Namespace }}-nginx-config
          items:
          - key: calvinadcert
            path: CalvinCollege-ad-CA.crt
          - key: calvinadcert
            path: ddbc78f4.0
      - name: phpconfig
        configMap:
          name: cs-{{ default "staging" .Release.Namespace }}-nginx-config
          defaultMode: 0777
          items:
          - key: phpconfigure
            path: php-configure-podstart.sh
---
{{ if eq .Release.Namespace "production" }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cs-php-{{ default "staging" .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cs-{{ default "staging" .Release.Namespace }}-php
  minReplicas: 2
  maxReplicas: 5
  #targetCPUUtilizationPercentage: 80
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 95
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 95
{{- end }}

