apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs-{{ default "staging" .Release.Namespace }}-php
  namespace: {{ default "staging" .Release.Namespace }}
  labels:
    tier: backend
  annotations:
    "builddate": "20220812-01"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cs-{{ default "staging" .Release.Namespace }}-php
      tier: backend
  template:
    metadata:
      labels:
        app: cs-{{ default "staging" .Release.Namespace }}-php
        tier: backend
        {{ if ne .Release.Namespace "production" }}name: cs-{{ .Release.Namespace }}{{- else }}hostname: cs{{- end }}
    spec:
      containers:
      - name: cs-{{ default "staging" .Release.Namespace }}-php
        image: php:8-fpm
        volumeMounts:
        - mountPath: /var/www/html
          name: webroot
          readOnly: true
        - mountPath: /etc/ssl/certs/CalvinCollege-ad-CA.crt
          name: config
          subPath: CalvinCollege-ad-CA.crt
          readOnly: true
        - mountPath: /etc/ssl/certs/ddbc78f4.0
          name: config
          subPath: ddbc78f4.0
          readOnly: true
      volumes:
      - name: webroot
        nfs:
          path: /export/csweb/html
          server: cswebnfs-int.k8s.cs.calvin.edu
      - name: config
        configMap:
          name: cs-{{ default "staging" .Release.Namespace }}-nginx-config
          items:
          - key: calvinadcert
            path: CalvinCollege-ad-CA.crt
          - key: calvinadcert
            path: ddbc78f4.0

