apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs-{{ default "staging" .Release.Namespace }}-nginx
  labels:
    tier: backend
spec:
  {{ if ne .Release.Namespace "production" }}replicas: 1{{- else }}replicas: 3{{- end }}
  selector:
    matchLabels:
      app: cs-{{ default "staging" .Release.Namespace }}-nginx
      tier: backend
  template:
    metadata:
      labels:
        app: cs-{{ default "staging" .Release.Namespace }}-nginx
        tier: backend
    spec:
      volumes:
      - name: webroot
        nfs:
          path: /calvincsaks/csweb/html
          server: calvincsaks.file.core.windows.net
      - name: config
        configMap:
          name: cs-{{ default "staging" .Release.Namespace }}-nginx-config
          items:
          - key: config
            path: site.conf
      - name: secretvolume
        secret:
          secretName: cs-htpasswd
      containers:
      - name: cs-{{ default "staging" .Release.Namespace }}-nginx
        image: nginx:stable
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/www/html
          name: webroot
          readOnly: true
        - mountPath: /etc/nginx/conf.d
          name: config
          readOnly: true
        - mountPath: /etc/secrets
          name: secretvolume
          readOnly: true
